version: '2.4'

services:
  node:
    labels:
      - stats
    image: registry.nspcc.ru/neo-bench/neo-go:bench
    logging:
      driver: "none"
    command: "node --config-path /config --privnet"
    ports: [ "20331:20331" ]
    healthcheck:
      interval: 5s
      retries: 15
      test: ['CMD', 'sh', '-c', 'echo | nc 127.0.0.1 20331']
      timeout: 10s
    environment:
      - ACC=single.acc
    volumes:
      - ./wallet.one.json:/config/wallet.json
      - ./go.protocol.privnet.single.yml:/config/protocol.privnet.yml

  healthy:
    image: alpine
    depends_on:
      node:
        condition: service_healthy
