version: '2.4'

services:
  node_one:
    labels:
      - stats
    image: registry.nspcc.ru/neo-bench/neo-sharp:bench
    container_name: neo-cli-node-one
    command: --rpc
    volumes:
      - ./wallet.one.json:/neo-cli/wallet.json
      - ./sharp.config.one.json:/neo-cli/config.json
      - ./sharp.protocol.json:/neo-cli/protocol.json
    healthcheck:
      interval: 5s
      retries: 50
      test:
        - CMD
        - bash
        - '-c'
        - /healthcheck.sh
      timeout: 10s

  node_two:
    labels:
      - stats
    image: registry.nspcc.ru/neo-bench/neo-sharp:bench
    container_name: neo-cli-node-two
    command: --rpc
    volumes:
      - ./wallet.two.json:/neo-cli/wallet.json
      - ./sharp.config.two.json:/neo-cli/config.json
      - ./sharp.protocol.json:/neo-cli/protocol.json
    healthcheck:
      interval: 5s
      retries: 50
      test:
        - CMD
        - bash
        - '-c'
        - /healthcheck.sh
      timeout: 10s

  node_three:
    labels:
      - stats
    image: registry.nspcc.ru/neo-bench/neo-sharp:bench
    container_name: neo-cli-node-three
    command: --rpc
    volumes:
      - ./wallet.three.json:/neo-cli/wallet.json
      - ./sharp.config.three.json:/neo-cli/config.json
      - ./sharp.protocol.json:/neo-cli/protocol.json
    healthcheck:
      interval: 5s
      retries: 50
      test:
        - CMD
        - bash
        - '-c'
        - /healthcheck.sh
      timeout: 10s

  node_four:
    labels:
      - stats
    image: registry.nspcc.ru/neo-bench/neo-sharp:bench
    container_name: neo-cli-node-four
    command: --rpc
    volumes:
      - ./wallet.four.json:/neo-cli/wallet.json
      - ./sharp.config.four.json:/neo-cli/config.json
      - ./sharp.protocol.json:/neo-cli/protocol.json
    healthcheck:
      interval: 5s
      retries: 50
      test:
        - CMD
        - bash
        - '-c'
        - /healthcheck.sh
      timeout: 10s

  healthy:
    image: alpine
    depends_on:
      node_one:
        condition: service_healthy
      node_two:
        condition: service_healthy
      node_three:
        condition: service_healthy
      node_four:
        condition: service_healthy
