version: "2.4"
networks:
  neo_go_network:
    name: neo_go_network
    ipam:
      config:
      - subnet: 172.200.0.0/24
        gateway: 172.200.0.254
services:
  healthy:
    image: alpine
    depends_on:
      node_1:
        condition: service_healthy
      node_2:
        condition: service_healthy
      node_3:
        condition: service_healthy
      node_4:
        condition: service_healthy
      node_5:
        condition: service_healthy
      node_6:
        condition: service_healthy
      node_7:
        condition: service_healthy
      node_8:
        condition: service_healthy
      node_9:
        condition: service_healthy
      node_10:
        condition: service_healthy
      node_11:
        condition: service_healthy
      node_12:
        condition: service_healthy
      node_13:
        condition: service_healthy
      node_14:
        condition: service_healthy
      node_15:
        condition: service_healthy
      node_16:
        condition: service_healthy
      node_17:
        condition: service_healthy
      node_18:
        condition: service_healthy
      node_19:
        condition: service_healthy
      node_20:
        condition: service_healthy
  node_1:
    labels:
    - stats
    container_name: neo_go_node_1
    image: registry.nspcc.ru/neo-bench/neo-go:bench
    command: node --config-path /config --privnet
    healthcheck:
      interval: 5s
      retries: 15
      test:
      - CMD
      - sh
      - -c
      - echo | nc 127.0.0.1 30333
      timeout: 10s
    environment:
    - ACC=dump.acc
    volumes:
    - ./go.protocol.privnet.1.yml:/config/protocol.privnet.yml
    - ./wallet.1.json:/config/wallet.json
  node_2:
    labels:
    - stats
    container_name: neo_go_node_2
    image: registry.nspcc.ru/neo-bench/neo-go:bench
    logging:
      driver: none
    command: node --config-path /config --privnet
    healthcheck:
      interval: 5s
      retries: 15
      test:
      - CMD
      - sh
      - -c
      - echo | nc 127.0.0.1 30334
      timeout: 10s
    environment:
    - ACC=dump.acc
    volumes:
    - ./go.protocol.privnet.2.yml:/config/protocol.privnet.yml
    - ./wallet.2.json:/config/wallet.json
  node_3:
    labels:
    - stats
    container_name: neo_go_node_3
    image: registry.nspcc.ru/neo-bench/neo-go:bench
    logging:
      driver: none
    command: node --config-path /config --privnet
    healthcheck:
      interval: 5s
      retries: 15
      test:
      - CMD
      - sh
      - -c
      - echo | nc 127.0.0.1 30335
      timeout: 10s
    environment:
    - ACC=dump.acc
    volumes:
    - ./go.protocol.privnet.3.yml:/config/protocol.privnet.yml
    - ./wallet.3.json:/config/wallet.json
  node_4:
    labels:
    - stats
    container_name: neo_go_node_4
    image: registry.nspcc.ru/neo-bench/neo-go:bench
    logging:
      driver: none
    command: node --config-path /config --privnet
    healthcheck:
      interval: 5s
      retries: 15
      test:
      - CMD
      - sh
      - -c
      - echo | nc 127.0.0.1 30336
      timeout: 10s
    environment:
    - ACC=dump.acc
    volumes:
    - ./go.protocol.privnet.4.yml:/config/protocol.privnet.yml
    - ./wallet.4.json:/config/wallet.json
  node_5:
    labels:
    - stats
    container_name: neo_go_node_5
    image: registry.nspcc.ru/neo-bench/neo-go:bench
    command: node --config-path /config --privnet
    healthcheck:
      interval: 5s
      retries: 15
      test:
      - CMD
      - sh
      - -c
      - echo | nc 127.0.0.1 30337
      timeout: 10s
    environment:
    - ACC=dump.acc
    volumes:
    - ./go.protocol.privnet.5.yml:/config/protocol.privnet.yml
  node_6:
    labels:
    - stats
    container_name: neo_go_node_6
    image: registry.nspcc.ru/neo-bench/neo-go:bench
    logging:
      driver: none
    command: node --config-path /config --privnet
    healthcheck:
      interval: 5s
      retries: 15
      test:
      - CMD
      - sh
      - -c
      - echo | nc 127.0.0.1 30338
      timeout: 10s
    environment:
    - ACC=dump.acc
    volumes:
    - ./go.protocol.privnet.6.yml:/config/protocol.privnet.yml
  node_7:
    labels:
    - stats
    container_name: neo_go_node_7
    image: registry.nspcc.ru/neo-bench/neo-go:bench
    logging:
      driver: none
    command: node --config-path /config --privnet
    healthcheck:
      interval: 5s
      retries: 15
      test:
      - CMD
      - sh
      - -c
      - echo | nc 127.0.0.1 30339
      timeout: 10s
    environment:
    - ACC=dump.acc
    volumes:
    - ./go.protocol.privnet.7.yml:/config/protocol.privnet.yml
  node_8:
    labels:
    - stats
    container_name: neo_go_node_8
    image: registry.nspcc.ru/neo-bench/neo-go:bench
    logging:
      driver: none
    command: node --config-path /config --privnet
    healthcheck:
      interval: 5s
      retries: 15
      test:
      - CMD
      - sh
      - -c
      - echo | nc 127.0.0.1 30340
      timeout: 10s
    environment:
    - ACC=dump.acc
    volumes:
    - ./go.protocol.privnet.8.yml:/config/protocol.privnet.yml
  node_9:
    labels:
    - stats
    container_name: neo_go_node_9
    image: registry.nspcc.ru/neo-bench/neo-go:bench
    logging:
      driver: none
    command: node --config-path /config --privnet
    healthcheck:
      interval: 5s
      retries: 15
      test:
      - CMD
      - sh
      - -c
      - echo | nc 127.0.0.1 30341
      timeout: 10s
    environment:
    - ACC=dump.acc
    volumes:
    - ./go.protocol.privnet.9.yml:/config/protocol.privnet.yml
  node_10:
    labels:
    - stats
    container_name: neo_go_node_10
    image: registry.nspcc.ru/neo-bench/neo-go:bench
    command: node --config-path /config --privnet
    healthcheck:
      interval: 5s
      retries: 15
      test:
      - CMD
      - sh
      - -c
      - echo | nc 127.0.0.1 30342
      timeout: 10s
    environment:
    - ACC=dump.acc
    volumes:
    - ./go.protocol.privnet.10.yml:/config/protocol.privnet.yml
  node_11:
    labels:
    - stats
    container_name: neo_go_node_11
    image: registry.nspcc.ru/neo-bench/neo-go:bench
    logging:
      driver: none
    command: node --config-path /config --privnet
    healthcheck:
      interval: 5s
      retries: 15
      test:
      - CMD
      - sh
      - -c
      - echo | nc 127.0.0.1 30343
      timeout: 10s
    environment:
    - ACC=dump.acc
    volumes:
    - ./go.protocol.privnet.11.yml:/config/protocol.privnet.yml
  node_12:
    labels:
    - stats
    container_name: neo_go_node_12
    image: registry.nspcc.ru/neo-bench/neo-go:bench
    logging:
      driver: none
    command: node --config-path /config --privnet
    healthcheck:
      interval: 5s
      retries: 15
      test:
      - CMD
      - sh
      - -c
      - echo | nc 127.0.0.1 30344
      timeout: 10s
    environment:
    - ACC=dump.acc
    volumes:
    - ./go.protocol.privnet.12.yml:/config/protocol.privnet.yml
  node_13:
    labels:
    - stats
    container_name: neo_go_node_13
    image: registry.nspcc.ru/neo-bench/neo-go:bench
    logging:
      driver: none
    command: node --config-path /config --privnet
    healthcheck:
      interval: 5s
      retries: 15
      test:
      - CMD
      - sh
      - -c
      - echo | nc 127.0.0.1 30345
      timeout: 10s
    environment:
    - ACC=dump.acc
    volumes:
    - ./go.protocol.privnet.13.yml:/config/protocol.privnet.yml
  node_14:
    labels:
    - stats
    container_name: neo_go_node_14
    image: registry.nspcc.ru/neo-bench/neo-go:bench
    logging:
      driver: none
    command: node --config-path /config --privnet
    healthcheck:
      interval: 5s
      retries: 15
      test:
      - CMD
      - sh
      - -c
      - echo | nc 127.0.0.1 30346
      timeout: 10s
    environment:
    - ACC=dump.acc
    volumes:
    - ./go.protocol.privnet.14.yml:/config/protocol.privnet.yml
  node_15:
    labels:
    - stats
    container_name: neo_go_node_15
    image: registry.nspcc.ru/neo-bench/neo-go:bench
    logging:
      driver: none
    command: node --config-path /config --privnet
    healthcheck:
      interval: 5s
      retries: 15
      test:
      - CMD
      - sh
      - -c
      - echo | nc 127.0.0.1 30347
      timeout: 10s
    environment:
    - ACC=dump.acc
    volumes:
    - ./go.protocol.privnet.15.yml:/config/protocol.privnet.yml
  node_16:
    labels:
    - stats
    container_name: neo_go_node_16
    image: registry.nspcc.ru/neo-bench/neo-go:bench
    logging:
      driver: none
    command: node --config-path /config --privnet
    healthcheck:
      interval: 5s
      retries: 15
      test:
      - CMD
      - sh
      - -c
      - echo | nc 127.0.0.1 30348
      timeout: 10s
    environment:
    - ACC=dump.acc
    volumes:
    - ./go.protocol.privnet.16.yml:/config/protocol.privnet.yml
  node_17:
    labels:
    - stats
    container_name: neo_go_node_17
    image: registry.nspcc.ru/neo-bench/neo-go:bench
    logging:
      driver: none
    command: node --config-path /config --privnet
    healthcheck:
      interval: 5s
      retries: 15
      test:
      - CMD
      - sh
      - -c
      - echo | nc 127.0.0.1 30349
      timeout: 10s
    environment:
    - ACC=dump.acc
    volumes:
    - ./go.protocol.privnet.17.yml:/config/protocol.privnet.yml
  node_18:
    labels:
    - stats
    container_name: neo_go_node_18
    image: registry.nspcc.ru/neo-bench/neo-go:bench
    logging:
      driver: none
    command: node --config-path /config --privnet
    healthcheck:
      interval: 5s
      retries: 15
      test:
      - CMD
      - sh
      - -c
      - echo | nc 127.0.0.1 30350
      timeout: 10s
    environment:
    - ACC=dump.acc
    volumes:
    - ./go.protocol.privnet.18.yml:/config/protocol.privnet.yml
  node_19:
    labels:
    - stats
    container_name: neo_go_node_19
    image: registry.nspcc.ru/neo-bench/neo-go:bench
    logging:
      driver: none
    command: node --config-path /config --privnet
    healthcheck:
      interval: 5s
      retries: 15
      test:
      - CMD
      - sh
      - -c
      - echo | nc 127.0.0.1 30351
      timeout: 10s
    environment:
    - ACC=dump.acc
    volumes:
    - ./go.protocol.privnet.19.yml:/config/protocol.privnet.yml
  node_20:
    labels:
    - stats
    container_name: neo_go_node_20
    image: registry.nspcc.ru/neo-bench/neo-go:bench
    command: node --config-path /config --privnet
    healthcheck:
      interval: 5s
      retries: 15
      test:
      - CMD
      - sh
      - -c
      - echo | nc 127.0.0.1 30352
      timeout: 10s
    environment:
    - ACC=dump.acc
    volumes:
    - ./go.protocol.privnet.20.yml:/config/protocol.privnet.yml
